### ISSUE TITLE
executalble works but shared library does not find resources

### ISSUE THREAD

**Issue by EvenSol** [equinor/neqsim-native#1]
If I compile to a exeutalbe file (.exe on windows) it works fine.

However if I compile into a shared library and try to use that in a c++ program in Visual Studio, it does not find resources and report the error:

Usage: C:\Users\esol\source\repos\neqsimtest\x64\Debug\neqsimtest.exe <filter>
start....
2024-09-12T11:34:18.814861700Z main ERROR Unrecognized format specifier [d]
2024-09-12T11:34:18.814861700Z main ERROR Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
2024-09-12T11:34:18.814861700Z main ERROR Unrecognized format specifier [thread]
2024-09-12T11:34:18.814861700Z main ERROR Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
2024-09-12T11:34:18.814861700Z main ERROR Unrecognized format specifier [level]
2024-09-12T11:34:18.814861700Z main ERROR Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
2024-09-12T11:34:18.814861700Z main ERROR Unrecognized format specifier [logger]
2024-09-12T11:34:18.814861700Z main ERROR Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
2024-09-12T11:34:18.814861700Z main ERROR Unrecognized format specifier [msg]
2024-09-12T11:34:18.814861700Z main ERROR Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
2024-09-12T11:34:18.814861700Z main ERROR Unrecognized format specifier [n]
2024-09-12T11:34:18.814861700Z main ERROR Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
2024-09-12T11:34:18.815859700Z main ERROR Unrecognized format specifier [d]
2024-09-12T11:34:18.815859700Z main ERROR Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
2024-09-12T11:34:18.815859700Z main ERROR Unrecognized format specifier [thread]
2024-09-12T11:34:18.815859700Z main ERROR Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
2024-09-12T11:34:18.815859700Z main ERROR Unrecognized format specifier [level]
2024-09-12T11:34:18.815859700Z main ERROR Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
2024-09-12T11:34:18.815859700Z main ERROR Unrecognized format specifier [logger]
2024-09-12T11:34:18.815859700Z main ERROR Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
2024-09-12T11:34:18.816860400Z main ERROR Unrecognized format specifier [msg]
2024-09-12T11:34:18.818868Z main ERROR Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
2024-09-12T11:34:18.818868Z main ERROR Unrecognized format specifier [n]
2024-09-12T11:34:18.819870600Z main ERROR Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
%d [%thread] %-5level %logger - %msg%n java.lang.RuntimeException: neqsim.util.exception.InvalidInputException: NeqSimDataBase:updateTable - Input path - Resource data/COMP.csv not found
        at neqsim.util.database.NeqSimDataBase.updateTable(NeqSimDataBase.java:459) ~[?:?]
        at neqsim.util.database.NeqSimDataBase.updateTable(NeqSimDataBase.java:447) ~[?:?]
        at neqsim.util.database.NeqSimDataBase.initH2DatabaseFromCSVfiles(NeqSimDataBase.java:502) [neqsimtest.exe:?]
        at neqsim.util.database.NeqSimDataBase.setDataBaseType(NeqSimDataBase.java:298) [neqsimtest.exe:?]
        at neqsim.util.database.NeqSimDataBase.setDataBaseType(NeqSimDataBase.java:281) [neqsimtest.exe:?]
        at neqsim.util.database.NeqSimDataBase.<init>(NeqSimDataBase.java:58) [neqsimtest.exe:?]
        at neqsim.util.database.NeqSimDataBase.hasComponent(NeqSimDataBase.java:404) [neqsimtest.exe:?]
        at neqsim.thermo.system.SystemThermo.addComponent(SystemThermo.java:301) [neqsimtest.exe:?]
        at neqsim.thermo.system.SystemSrkCPA.addComponent(SystemSrkCPA.java:80) [neqsimtest.exe:?]
        at neqsim.process.TestProcess.main(TestProcess.java:40) [neqsimtest.exe:?]
        at java.base/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH) [neqsimtest.exe:?]
Caused by: neqsim.util.exception.InvalidInputException: NeqSimDataBase:updateTable - Input path - Resource data/COMP.csv not found
        ... 11 more
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "COMP" not found (this database is empty); SQL statement:
select count(*) from comp WHERE NAME='nitrogen' [42104-232]
        at neqsim.util.database.NeqSimDataBase.hasComponent(NeqSimDataBase.java:415)
        at neqsim.thermo.system.SystemThermo.addComponent(SystemThermo.java:301)
        at neqsim.thermo.system.SystemSrkCPA.addComponent(SystemSrkCPA.java:80)
        at neqsim.process.TestProcess.main(TestProcess.java:40)
        at java.base@22.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.lang.RuntimeException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "COMP" not found (this database is empty); SQL statement:
select count(*) from comp WHERE NAME='nitrogen' [42104-232]
        at neqsim.util.database.NeqSimDataBase.getResultSet(NeqSimDataBase.java:222)
        at neqsim.util.database.NeqSimDataBase.hasComponent(NeqSimDataBase.java:406)
        ... 4 more
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "COMP" not found (this database is empty); SQL statement:
select count(*) from comp WHERE NAME='nitrogen' [42104-232]
        at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:7932)
        at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:7916)
        at org.h2.command.Parser.readTableOrView(Parser.java:7895)
        at org.h2.command.Parser.readTablePrimary(Parser.java:1769)
        at org.h2.command.Parser.readTableReference(Parser.java:2249)
        at org.h2.command.Parser.parseSelectFromPart(Parser.java:2702)
        at org.h2.command.Parser.parseSelect(Parser.java:2810)
        at org.h2.command.Parser.parseQueryPrimary(Parser.java:2692)
        at org.h2.command.Parser.parseQueryTerm(Parser.java:2547)
        at org.h2.command.Parser.parseQueryExpressionBody(Parser.java:2526)
        at org.h2.command.Parser.parseQueryExpressionBodyAndEndOfQuery(Parser.java:2519)
        at org.h2.command.Parser.parseQueryExpression(Parser.java:2512)
        at org.h2.command.Parser.parseQuery(Parser.java:2479)
        at org.h2.command.Parser.parsePrepared(Parser.java:610)
        at org.h2.command.Parser.parse(Parser.java:581)
        at org.h2.command.Parser.parse(Parser.java:556)
        at org.h2.command.Parser.prepareCommand(Parser.java:484)
        at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
        at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
        at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:94)
        at neqsim.util.database.NeqSimDataBase.getResultSet(NeqSimDataBase.java:216)
        ... 5 more

**Comment by EvenSol** [comment]
solved in updated code.
